### PR TITLE
Nikhil Kamineni - Complete

### PR DESCRIPTION
**Pull request by nikhilkamineni**

### CODE REVIEW

**Comment by mixelpixel** [comment]
Thanks for putting your name in the GitHub PR title!!!

Great to see you are making git commits often and with useful comments 😄 

Looked at your index.html - no console log errors, that's what we like to see.

Myself or another TA will try and check back when you're done - Great job so far 👍

**Comment by tsj7** [comment]
Project looks great, indentation and spacing are very well laid out, easy to read and understand. Well done.

**Comment by nikhilkamineni** [comment]
Working on converting to rem and %.

**Comment by nikhilkamineni** [comment]
Should be done with everything

**Pull request closed without merging**
