### PR TITLE
Tasks completed

### PR DESCRIPTION
**Pull request by cwindeknecht**
Boring at the moment.  Going to keep messing around with it.

### CODE REVIEW

**Comment by wlharvey4** [comment]
cwindeknecht:
Please be sure to put your name in the title of the pull request!
You made a whole lot changes with just one commit; try to make commits often as you are working, and make a lot more.

Some thoughts on making commit messages:
1) The first line should be a title or description of the problem addressed in the commit
2) The second line should be blank
3) The third and subsequent lines should be detailed messages of files changed, changes made, why, how, and the problems solved.

Getting into a habit of making your commit messages this way will make you an invaluable member of your team by giving the reviewing members the information they need to assess your pull request quickly and easily.  These details will tell them if this pull request is something they want and whether it might have potential problems buried inside it.  The more information you give them, the more likely you will get good reviews coming back and you will get more pull requests accepted.

Wesley

**Comment by mixelpixel** [comment]
@wlharvey4 Hey, just showing off some stuff to Mr. Windeknecht :)

(Awesome PR review btw!)

**Comment by cwindeknecht** [comment]
Going to start over from scratch, this has turned into a pile of garbage.  Think it would help my understand to just start over.

**Comment by mixelpixel** [comment]
Have taken the same approach MANY times myself 😄

**Pull request closed without merging**
