### PR TITLE
Patrick made me do it // Daniel Lara / responsive-web-design_inProgress

### PR DESCRIPTION
**Pull request by Dan-Lara**

### CODE REVIEW

**Comment by wlharvey4** [comment]
Daniel,
Nice job with the edits.  We are also trying to teach how to make effective commits and pull requests, so I will take the opportunity here to offer some suggestions.

Make commits often as you are working.
Each commit message should be structured like:
1) First line should be a title or description of the problem or issue being addressed
2) Second line should be blank
3) Third and subsequent lines should have detailed information about the files changed, where, why, and how, and the problems or issues fixed by the changes.

Getting into the habit of making these kinds of commit messages will help reviewing members of your team quickly understand what changes you are asking to be injected into the code base, why, and whether that is something they want, or alert them to potential problems.  Making them this way will also result in more detailed responses from them, giving you the guidance you need to fix any problems they see; finally, this method will result in more of your pull requests being accepted, and that will make you an invaluable member of their team.

Wesley

**Comment by wlharvey4** [comment]
Daniel,
That last commit looks beautiful.  Great job.

**Comment by mixelpixel** [comment]
@Dan-Lara lol 😄  Nice work! Notice, if you scroll up to your commit msgs, you can click on the `...` and expand the "body" of the commit message 🏆 

I see no errors in the console when I load your page - always a good sign! Love the way the "Innovation On Demand" goes onto the circle image when the window gets compressed. Also very nice how the "Aliquam" text resizes and the window compresses.

Looking at it in with the Chrome mobile device emulators, the smaller devices seem to have the page positioning suggering under the navbar. Only suggestion I could make - if you are still hackin' on it, maybe get the navbar to compress as well? Otherwise, looks like you are having fun with the week's material 🎉  Keep up the good work!

**Comment by Dan-Lara** [comment]
Thanks for the feedback guys I appreciate the tips. 👍

**Pull request closed without merging**
